### ISSUE TITLE
Crash when loading

### ISSUE THREAD

**Issue by WenXin20** [Khazoda/Plushables#1]
Forge v14.23.5.2825
Plushable v0.2
I got this crash when trying to load the game up.
[Crash Report](https://gist.github.com/WenXin20/45b78c6afe13503a7fb29a6e8fe4b15d)

**Comment by DWX12** [comment]
I'm getting a similar crash:

https://hastebin.com/xabimimaqo.rb

**Comment by khazoda** [comment]
Fixed
