### ISSUE TITLE
[Suggestion] Play sound file upon interaction

### ISSUE THREAD

**Issue by DWX12** [Khazoda/Plushables#2]
You mentioned possible animations in the future and I thought sounds upon interaction would be a cool addition and maybe even a config file to be able to change or dictate what sounds each plushie should make.

Thank you for creating such a cool mod and all of your work and effort.

**Comment by DWX12** [comment]
If you were going to add in any of your own sound effects, I would expect nothing less than cute versions of regular mob sounds. ;)

**Comment by khazoda** [comment]
Thank you for the great suggestion, in the newest version of the mod for 1.19 I've incorporated custom sounds for both the builder block and for shift right clicking plushables to pick them up. In the near future I definitely plan to include sounds on interaction with some of the plushables 😄
