### ISSUE TITLE
New Plushables Suggestion - Tiger

### ISSUE THREAD

**Issue by BusterBean** [Khazoda/Plushables#36]
Maybe siberian tigers?

**Comment by khazoda** [comment]
Thanks for the suggestion, I've added it to the roadmap for potential new plushies 😊

**Comment by khazoda** [comment]
Added the siberian tiger as `Plushable Tiger` in commit 5beb0783ea567cd588bfec88e1505f42d841e6f9. Will release with Version 1.1.3.
