### ISSUE TITLE
[Suggestion] Add a way for others to add their own plusies

### ISSUE THREAD

**Issue by OakBricks-old** [Khazoda/Plushables#4]
title

this can come in either a modding api (would require some coding to make a plush) or a resource pack-like system where the user downloads a zip file from someone and the plush could show up in a separate tab or the same inventory tab

**Comment by khazoda** [comment]
This is something I'd like to implement for simple block plushables in future. Once the mod has had a few stable releases I'll revisit this idea, with datapack generated plushables. Thank you for the suggestion 🙂
