### ISSUE TITLE
Lavender backport for 1.20.1

### ISSUE THREAD

**Issue by GeoDerp** [Khazoda/Plushables#55]
Greetings, Happy to help with this.
Was wondering how doable would it be to back port the updates from 1.20.2 to 1.20.1. *(in particular Patchouli to Lavender requirement)* 

*I may have a look commit differences in the near future myself and see if I can submit a working pull request. If you will accept the help that is.*

**Comment by khazoda** [comment]
Hi @GeoDerp, sorry for the late follow-up to this.

If you submit a PR I will merge it and release the version if it's in a workable state.

However, I'm planning on deprecating this version of plushables, with plushables lite's current featureset becoming the main mod. 

The truth is plushables in its current form is quite dependent on third party libraries and has code that'd be a pain to update to newer versions of Minecraft. I have quite a few other mods I'm actively updating now, so my free time is split between these projects as well as plushables.

I'm very happy with plushables lite (which has no dependencies), and want to keep supporting that mod as the main mod going forward. I hope you can understand.

Thanks for the interest in plushables :)

**Comment by khazoda** [comment]
closing due to Plushables being actively supported dependency-free on 1.21.1+
