### ISSUE TITLE
[Request] Can you add compatibility with Trinkets mod

### ISSUE THREAD

**Issue by Zunwolf1896** [Khazoda/Plushables#56]
Hello!
here to request compatibility with the [Trinkets mod](https://www.curseforge.com/minecraft/mc-mods/trinkets) this would allow players to wear the plushies on their head and not have to give up on their armoured helmets, making the plushies a cosmetic hat they can add on without losing armour points.

**Comment by khazoda** [comment]
I explored making Plushables compatible with both the Trinkets and Accessories mods, but each one required integration code to work properly (trinkets doesn't render the model by default, and accessories had strange default rendering that I would have had to change).

Until a baubles-like mod that's fully data driven for this mod's requirements is made, this is going to remain unfixed, sorry.
